FROM python:3.7

# We copy just the requirements.txt first to leverage Docker cache

RUN mkdir /watchapp

WORKDIR /watchapp

ADD . /watchapp/

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

#EXPOSE 8000

#CMD ["python", "/watchapp/app.py"]
CMD ["pytest", "/watchapp/test.py"]